name: Security Checks

on:
  schedule:
    - cron: "0 19 * * 5"
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run security audit
        run: |
          yarn audit --level high --groups dependencies || exit 0

      - name: Check for vulnerabilities in example
        run: |
          cd example
          yarn audit --level high --groups dependencies || exit 0

  codeql:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
